# apps/transportation/urls.py

from django.urls import path # <-- Added path import
from rest_framework.routers import DefaultRouter
from .views import (
    VehicleViewSet, 
    DriverViewSet, 
    ShipmentViewSet, 
    MyAssignedJobsView # <-- Added new view import
)

# --- Router Configuration ---
router = DefaultRouter()
router.register(r"vehicles", VehicleViewSet, basename="vehicle")
router.register(r"drivers", DriverViewSet, basename="driver")
router.register(r"shipments", ShipmentViewSet, basename="shipment")

# --- URL Patterns ---
# Start with the patterns generated by the router
urlpatterns = router.urls

# Add the new dedicated ListAPIView
# Assuming the root URL config already prefixes this app's URLs with 'transportation/' 
# or a similar path. The API path will likely be /api/v1/transportation/jobs/assigned-to-me/
urlpatterns += [
    path('jobs/assigned-to-me/', MyAssignedJobsView.as_view(), name='my-assigned-jobs'),
]