# Generated by Django 5.2.6 on 2025-10-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="status",
        ),
    ]
