# Generated by Django 5.2.6 on 2025-12-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_jobtimeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="proof_of_delivery_image",
            field=models.ImageField(blank=True, null=True, upload_to="pod/"),
        ),
    ]
