# Generated by Django 5.2.6 on 2025-12-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_job_job_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="cwt_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="For CWT pricing",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="flat_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="For Flat Rate pricing",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="For Hourly pricing",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("RESIDENTIAL", "Residential (Movers)"),
                    ("COMMERCIAL", "Commercial (Freight)"),
                ],
                default="COMMERCIAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="pallet_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="For Commercial: Number of pallets", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="pricing_model",
            field=models.CharField(
                choices=[
                    ("HOURLY", "Hourly Rate + Travel Fee"),
                    ("FLAT_RATE", "Flat Lane Rate"),
                    ("CWT", "CWT (Per 100 lbs)"),
                ],
                default="FLAT_RATE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="room_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="For Residential: Number of rooms", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="travel_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="For Hourly pricing",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="volume_cf",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="For Residential: Volume in cubic feet",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="weight_lbs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="For Commercial: Weight in lbs",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="service_type",
            field=models.CharField(
                blank=True,
                help_text="Legacy field, use job_type for new logic",
                max_length=50,
                null=True,
            ),
        ),
    ]
