# Generated by Django 5.2.6 on 2025-12-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_job_cwt_rate_job_flat_rate_job_hourly_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="bol_number",
            field=models.CharField(
                blank=True,
                help_text="For Commercial: Bill of Lading Number",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="crew_size",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="For Residential: Number of movers required",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="estimated_items",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="For Residential: Inventory list (e.g. {'sofa': 2})",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="is_hazardous",
            field=models.BooleanField(
                default=False, help_text="For Commercial: Hazardous material flag"
            ),
        ),
    ]
