# Generated by Django 5.2.6 on 2025-12-18 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("origin", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("small", "Small (< 50 lbs)"),
                            ("medium", "Medium (50-150 lbs)"),
                            ("large", "Large (150-500 lbs)"),
                            ("pallet", "Pallet (500+ lbs)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estimated_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("estimated_days", models.CharField(max_length=20)),
                ("distance_miles", models.IntegerField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote Request",
                "verbose_name_plural": "Quote Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
