# Generated by Django 5.2.6 on 2025-12-21 18:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region_code",
                    models.CharField(
                        help_text="e.g. 'ON', 'BC', 'KE'", max_length=10, unique=True
                    ),
                ),
                (
                    "tax_name",
                    models.CharField(
                        help_text="e.g. 'HST', 'GST+PST', 'VAT'", max_length=50
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4, help_text="e.g. 0.1300 for 13%", max_digits=5
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_rule_applied",
            field=models.JSONField(
                blank=True,
                help_text="Snapshot of the TaxRule used (rate, name, region)",
                null=True,
            ),
        ),
    ]
