# Generated by Django 5.2.6 on 2025-10-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transportation", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="proof_of_delivery_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="proof_of_delivery/"
            ),
        ),
    ]
