# Generated by Django 5.2.6 on 2025-12-20 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transportation", "0003_shipment_proof_of_delivery_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="proof_of_delivery_signature",
            field=models.ImageField(blank=True, null=True, upload_to="signatures/"),
        ),
        migrations.CreateModel(
            name="ShipmentPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="proof_of_delivery/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="transportation.shipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
