# Generated by Django 5.2.6 on 2025-12-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transportation", "0004_shipment_proof_of_delivery_signature_shipmentphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentphoto",
            name="photo_type",
            field=models.CharField(
                choices=[
                    ("PRE_MOVE", "Pre-Move Condition"),
                    ("POST_MOVE", "Post-Move Condition"),
                    ("POD", "Proof of Delivery"),
                    ("OTHER", "Other"),
                ],
                default="POD",
                max_length=20,
            ),
        ),
    ]
